# Generated by Django 4.2.2 on 2023-06-08 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(default='empty', unique=True)),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название')),
                ('slug', models.SlugField(default='empty', unique=True)),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('image', models.ImageField(blank=True, upload_to='products/', verbose_name='Изображение')),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='Дата публикации')),
                ('publisher', models.CharField(max_length=100, null=True)),
                ('developer', models.CharField(max_length=100, null=True)),
                ('release_date', models.DateField(verbose_name='Дата выпуска')),
                ('genre', models.ManyToManyField(related_name='genre', to='games.genre')),
            ],
            options={
                'verbose_name': 'Игра',
                'verbose_name_plural': 'Игры',
                'ordering': ('pub_date',),
            },
        ),
    ]
